<script>
 debugger
 ejecuta();
 async function ejecuta() {
  try {
   const r1 =
    await Promise.resolve("Hola")
   document.write(
    `Éxito 1: ${r1}<br>`)
  } catch (e) {
   document.write(
    `Falló 1: ${e.message}<br>`)
  }
  try {
   const r2 = await Promise.reject(
    new Error("ouch"))
   document.write(`Éxito 2 ${r2}`)
  } catch (e) {
   document.write(
    `Falló 2: ${e.message}<br>`)
  }
 }
</script>